services:
  tutorials-jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.hub
    image: vector-modelling-tutorial-hub:latest
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - tutorials-hub-data:/srv/jupyterhub
      - tutorials-user-data:/srv/jupyter
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/srv/jupyterhub/.env:ro
      - ./data:/srv/shared:ro
    networks: [jhub]

  tutorials-nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - tutorials-jupyterhub
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt:ro
    networks: [jhub]

  tutorials-singleuser:
    build:
      context: .
      dockerfile: Dockerfile.singleuser
    image: vector-modelling-tutorial-user:latest
    profiles: ["build"]

networks:
  jhub: {}

volumes:
  tutorials-hub-data:
  tutorials-user-data: