FROM jupyterhub/jupyterhub:5.2.1

RUN apt-get update && apt-get install -y sqlite3

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
    dotenv \
    dockerspawner \
    jupyterhub-nativeauthenticator \
    jupyterhub-idle-culler \
    jupyter \
    jupyterlab

# Copy initialization script
COPY init_jhub.sh /usr/local/bin/init_jhub.sh
RUN chmod +x /usr/local/bin/init_jhub.sh

# Run init script at container start
CMD ["bash", "/usr/local/bin/init_jhub.sh"]
