services:
  jupyterlabs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-modelling-tutorials
    environment:
      - N_USERS=1
    image: vector-modelling-tutorials:latest
    restart: unless-stopped
    ports:
      - "8000-8099:8000-8099"