# Python + Lab base
FROM kerguler/vector-modelling-tutorial-base:latest

USER root

COPY ./src/custom /srv/jupyterhub/custom

COPY init_tutorials.sh /usr/local/bin/init_tutorials.sh
RUN chmod +x /usr/local/bin/init_tutorials.sh

ENTRYPOINT ["tini", "-g", "--", "init_tutorials.sh"]
CMD ["jupyterhub-singleuser"]
