FROM jupyter/nbviewer

CMD ["python3", "-m", "nbviewer", "--provider=local", "--config=/srv/nbviewer_config.py", "--base-url=/tutorials-viewer/", "--localfiles=/srv/tutorials", "--template-path=/srv/templates", "--static-path=/srv/templates/static", "--port=8080", "--no-cache"]