FROM jupyter/nbviewer

CMD ["python3", "-m", "nbviewer", "--base-url=/tutorials-viewer/", "--no-cache", "--template-path=/srv/templates", "--static-path=/srv/templates/static", "--localfiles=/srv/tutorials", "--port=8080"]