server {
  listen 80;
  server_name _;

  # If uploads can be big (e.g., notebooks, data)
  client_max_body_size 256m;
  proxy_read_timeout 86400;

  location = /tutorials/viewer {
    rewrite ^/tutorials/viewer$ /tutorials/viewer/ permanent;
  }

  location /tutorials/viewer/ {
        alias /srv/tutorials-html/;     # path in the nginx container
        autoindex on;                   # optional: show directory listing
        index index.html;
        try_files $uri $uri/ =404;
  }

  location /tutorials/ {
    proxy_pass http://tutorials-jupyterhub:8000/tutorials/;
    proxy_http_version 1.1;

    # Preserve host and client IP chain
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;

    # Trust the proto from the OUTER proxy if it sets it (https/http)
    proxy_set_header X-Forwarded-Proto $scheme;

    # WebSockets
    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        "upgrade";

    # Avoid buffering WS traffic
    proxy_buffering off;
  }

  # redirect root to /tutorials
  location = / {
    return 302 https://$host/tutorials/;
  }
}
