/* 
 *  This code was automatically generated by PopJSON (v.1.3.5) for Population (v.0.1.7)
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  See the GNU General Public License for more details:
 *  <https://www.gnu.org/licenses/>
 */

#include <math.h>
#include "population.h"

#define CHECK(x) (isnan(x) || isinf(x))

#define NumPar 3
#define NumPop 1
#define NumInt 2
#define NumEnv 1

#define param_dL_1 0
#define param_dL_2 1
#define param_dL_3 2

#define larva_dev 0


double dmin(double a, double b) { return a < b ? a : b; }
double dmax(double a, double b) { return a > b ? a : b; }

int TIME;
int TIMEF;

double *model_param;
double *envir_temp;

double int_larva_dev_mean;
double int_larva_dev_stdev;


#define briere1(T,L,R,a) (((((T) <= (L))) ? (0.0) : (((((T) >= (R))) ? (0.0) : (dmax(0.0, ((a) * (T) * ((T) - (L)) * sqrt(((R) - (T))))))))))
#define briere1_dev(T,L,R,a) (dmin(10000000000000, (1.0 / briere1((T), (L), (R), (a)))))
double define_briere1(double T, double L, double R, double a) {return ((((T) <= (L))) ? (0.0) : (((((T) >= (R))) ? (0.0) : (dmax(0.0, ((a) * (T) * ((T) - (L)) * sqrt(((R) - (T)))))))));}
double define_briere1_dev(double T, double L, double R, double a) {return dmin(10000000000000, (1.0 / briere1((T), (L), (R), (a))));}

void prepare_tprobs(int numcol, double *ttprobs, double *tprobs) {
    int rA, rB, i = 0;
    double sum;
    for (i=0, rB=0; rB<numcol; rB++) {
        sum = 1.0;
        for (rA=0; rA<numcol; rA++, i++) {
            tprobs[i] = sum <= 0.0 ? 1.0 : ttprobs[i] / sum;
            sum -= ttprobs[i];
        }
    }
}

void init(int *no, int *np, int *ni, int *ne, int *st) {
    spop2_set_eps(1e-13);

    *no = NumPop;
    *np = NumPar;
    *ni = NumInt;
    *ne = NumEnv;
    *st = 0;
}

void parnames(char **names, double *param, double *parmin, double *parmax) {
    char temp[NumPop+NumPar+NumInt+NumEnv][256] = {
        "larva",
        "param_dL_1", "param_dL_2", "param_dL_3",
        "int_larva_dev_mean", "int_larva_dev_stdev",
        "temp",
    };

    int i;
    for (i=0; i<(NumPop+NumPar+NumInt+NumEnv); i++)
        names[i] = strdup(temp[i]);

    param[param_dL_1] = 10;
    parmin[param_dL_1] = 10;
    parmax[param_dL_1] = 10;
    param[param_dL_2] = 30;
    parmin[param_dL_2] = 30;
    parmax[param_dL_2] = 30;
    param[param_dL_3] = 0.0001;
    parmin[param_dL_3] = 0.0001;
    parmax[param_dL_3] = 0.0001;
}

void destroy(void) {
}

void sim(int *tf, int *rep, double *envir, double *pr, double *y0, char **file_from, char **file_to, double *ret, double *iret, int *success) {

    char *file0 = *file_from;
    char *file1 = *file_to;

    TIME = 0;
    TIMEF = *tf;

    model_param = pr;

    envir_temp = envir + 1; envir += (int)round(*envir) + 1;


    population larva;

    number num = numZERO;
    char arbiters[2];
    number key[2];
    number size_larva;
    number completed_larva[2];
    double par[2];

    FILE *file;
    number *buff = 0;
    unsigned int buffsz = 0;
    if (file0 && file0[0]!=' ') {
        file = fopen(file0,"rb");
        if (!file) {
            *success = 0;
            goto endall;
        }
        rewind(file);
    }

    if (file0 && file0[0]!=' ') {
        fread(&buffsz, sizeof(unsigned int), 1, file);
        buff = (number *)malloc(buffsz);
        fread(buff, buffsz, 1, file);
        larva = spop2_loadstate(buff);


        free(buff);

    } else {
        arbiters[0] = ACC_ERLANG;
        key[0] = numZERO;
        arbiters[1] = STOP;
        key[1] = numZERO;
        larva = spop2_init(arbiters, DETERMINISTIC);
        if (y0[0]) { num.d = y0[0]; spop2_add(larva, key, num); }


    }

    if (file0 && file0[0]!=' ') {
        fclose(file);
    }

    int_larva_dev_mean = 0.0;
    int_larva_dev_stdev = 0.0;

    size_larva = spop2_size(larva);

    ret[0] = size_larva.d;
    if (CHECK(ret[0])) {goto endall;};

    ret += 1;

    for (TIME=1; TIME<TIMEF; TIME++) {
        int_larva_dev_mean = briere1_dev(envir_temp[(int)(TIME-1)], model_param[param_dL_1], model_param[param_dL_2], model_param[param_dL_3]);
        int_larva_dev_stdev = sqrt(int_larva_dev_mean);

        if (*rep >= 0) {
                par[0] = int_larva_dev_mean;
                par[1] = int_larva_dev_stdev;
                spop2_step(larva, par, &size_larva, completed_larva, 0);









        }

        ret[0] = size_larva.d;
        if (CHECK(ret[0])) {goto endall;};

        ret += 1;

        iret[0] = int_larva_dev_mean;
        if (CHECK(iret[0])) {goto endall;};
        iret[1] = int_larva_dev_stdev;
        if (CHECK(iret[1])) {goto endall;};



        iret += 2;

    }

  endall:

    *success = TIME;

    if (file1 && file1[0]!=' ') {
        file = fopen(file1,"wb");
        if (!file) {
            *success = 0;
        } else {
            rewind(file);

            buffsz = spop2_buffsize(larva);
            buff = spop2_savestate(larva);
            fwrite(&buffsz, sizeof(unsigned int), 1, file);
            fwrite(buff, buffsz, 1, file);
            free(buff);

            fclose(file);
        }
    }

    spop2_free(&larva);

}

int main(int argc, char *argv[]) {
    return 0;
}


