#' Run a simulation
#'
#' @description function to run simulations
#'
#' @param parcels data.frame or data.table describing the patches. Required columns: 'ID': unique identifier, 'POP': population size, 'Kfix': fix carrying capacity for larvae and pupae, 'Kvar': variable carrying capacity for larvae and pupae, 'STATION': meteorological station identifier (optional), 'DIFF_ALT': difference between meteorological station altitude and average altitude of the patch (optional).
#' @param vector string. "Ae. albopictus", "Ae. albopictus (D)" or "Ae. aegypti". Default is "Ae. albopictus".
#' @param virus string.  "DEN" (dengue), "ZIK" (zika) or "CHI" (chikungunya). Default is "DEN" (dengue) virus.
#' @param gdata list of parameters. Can be generated using `build_gdata` function.
#' @param ldata matrix of local data
#' @param meteo data.frame or data.table reporting the daily meteorological data for each meteorological station. Required columns: 'ID', 'DATE', 'RR': daily precipitation (mm), 'TP': daily mean temperature (degrees)
#' @param mMov double matrix
#' @param start_date date in '\%Y-\%m-\%d' format
#' @param end_date date in '\%Y-\%m-\%d' format
#' @param nYR_init numeric. Number of years used to initialize the population dynamics (default is 1)
#' @param n_sim integer
#' @param introduction_pts  data.frame or data.table describing the introduction of individuals. Can be generated by [build_E_random()] function (see function documentation for additional details on the structure.
#' @param prev_control data.frame or data.table describing preventive control measure implemented. Required columns: 'action', 'loc', 'start', 'end', 'p' (see details)
#' @param ref_norm numeric, rainfall normalization factor / reference value (>0)
#' @param u0 data.frame describing the initial population stage for each compartment in each parcel. Can be generated by [iniState()] function (see documentation of the function for more details on the structure).
#' @param v0 data.frame describing the initial population and time-dependant parameters state.  Can be generated by [iniState()] function (see documentation of the function for more details on the structure).
#'
#' @param verbose logical. Provide additional information during process
#'
#' @param initMosq numeric. Number of eggs in each patch at t0 (default is 100000).
#'
#'  @details
#'  Preventive control content:
#'  'action' column must be strings 'K', 'L' or 'A'. 'K': Source reduction (removal or destruction of breeding sites); 'L': Chemical Larviciding; 'A': Fogging or Area Spraying (targets adult mosquitoes)
#'  'loc' column must be a parcel id
#'  'start' is the first day of implementation of the measure
#'  'end' is the last day of implementation of the measure (the control is implemented every day in between)
#'  'p' must be a number between 0 and 1. It is for the "K" action: the proportion of sites daily removed during the action ; for the "A" action: the additional daily mortality of adults due to action and for the "L" action: the additional daily mortality of larvae due to larvicide
#'
#'
#' @importFrom SimInf mparse run trajectory
#' @importFrom magrittr is_greater_than
#' @importFrom data.table `:=` setDT setcolorder
#' @importFrom utils capture.output
#'
#' @return data.table
#'
#' @export


run_arbocartoR <- function(parcels,

                        vector = "Ae. albopictus (D)",
                        virus = "DEN",
                        gdata = NULL,

                        ldata = NULL,

                        meteo = NULL,
                        mMov = NULL,

                        start_date = NULL,
                        end_date = NULL,
                        nYR_init = 1,
                        n_sim = 1,
                        introduction_pts = NULL,
                        prev_control = NULL,
                        ref_norm = 100,

                        u0 = NULL,
                        v0 = NULL,
                        initMosq = 100000,
                        verbose = F){

  if(is.null(ldata) & is.null(meteo))
    stop("you must provide either ldata matrix or meteorological dataset (meteo)")

  if(!is.null(ldata) & !is.null(mMov))
    stop("you can not provide a new human contact matrix if you provide ldata. Please generate a new ldata with the current mMov and set mMov to NULL")

  if((is.null(start_date) | is.null(end_date)) & is.null(meteo))
    stop("if the meteorological dataset (meteo) is not provided, you must provide start en end dates for simulations (arguments: start_date, end_date)")

  if(n_sim < 1)
    stop('The number of simulations must be positive a positive integer')

  ####################
  ### General data ###
  ####################
  # input data:
  # parcels : table where each row is a node and columns are attributes
  # meteo: table with four columns nodeID, date, daily rainfall, daily mean temperature

  check_parcels(parcels)

  ############################
  ### Model initialization ###
  ############################

  if(is.null(start_date))
    start_date <- min(meteo$DATE) %>% as.Date

  if(is.null(end_date))
    end_date <- max(meteo$DATE) %>% as.Date

  if(!is.null(meteo))
    if(start_date < min(meteo$DATE) | end_date > max(meteo$DATE))
      stop("start_date and end_date must be included in meteorological records")

  ## Simulation period ##
  TS_sim <- sim_time_serie(start_date, end_date, nYR_init)

  # Check and filter meteo

  if(!is.null(meteo))
  meteo <- filter_meteo(parcels, meteo, TS_sim)

  # preventive prev_control check
  if(!is.null(prev_control))
    check_prev_control(prev_control, TS_sim$time_serie_output_d)

  ###########################################
  ## Create u0, v0 and compartment objects ##
  ###########################################

  if(verbose)
    message("## Initialization ##")

  init <- iniState(parcels,
                   diapause = (vector == "Ae. albopictus (D)"),
                   initMosq = initMosq)

  if(! is.null(u0) | !is.null(v0)){
    nYR_init = 0
    cat("as u0 and/or v0 is not null, the model is not initialized and start from the predefined population state")
    }
  if(is.null(u0))
    u0 <- init$u0
  if(is.null(v0))
    v0 <- init$v0


  ###############################################################
  ## Define the compartments, gdata and stochastic transitions ##
  ###############################################################
  ## Stochastic transitions are related to the epidemiological model and the life cycle of infected mosquitoes.

  #### Global data (general parameters) ####

  gdata <- check_gdata(gdata, vector, virus)

  ##################
  ## Define ldata ##
  ##################
  ## ldata is a vector of local data: daily temperature, kL and  kP and number of non infected mosquitoes in each stage.
  ## the first item (index = 0) is the number of simulated days, it will be used to daily update v0 with ldata content.
  ## Now improve this and use time to index data in ldata (local data).

  if(is.null(ldata)){
    if(verbose)
      message("## Format local data ##")
    ldata <- build_ldata(parcels = parcels,
                         meteo = meteo,
                         gdata = gdata,
                         vector = vector,
                         virus = virus,
                         mMov = mMov,
                         prev_control = prev_control,
                         start_date = start_date,
                         end_date = end_date,
                         nYR_init = nYR_init)
  } else {
    if(ldata[1,1] != length(TS_sim$time_serie_date))
      stop(paste0("The number of days considered in ldata (",ldata[1,1],") is not consistent with the simulated period and the number of initialization years (",length(TS_sim$time_serie_date)," days)."))

    if(ncol(ldata) != nrow(parcels))
      stop(paste0("The number of patch considered in ldata (",ncol(ldata),") is not consistent with the number of patchs in parcels (",nrow(parcels),")."))
  }

  ##############
  ## Diapause ##
  ##############

  # Calculates days for diapause over all the simulated period and build pts_fun
  if( !is.null(gdata$startFav) & !is.null(gdata$endFav)){
    diapause_interv <- diapause(startFav = gdata$startFav,
                                endFav   = gdata$endFav,
                                TS_sim   = TS_sim)
  } else diapause_interv <- NULL

  gdata  %<>% .[which(!names(gdata) %in% c("startFav","endFav"))] %>% unlist
  mode(gdata) <- "numeric"

  if(verbose)
    message("## Build stochastic transitions ##")
  #### Stochastic transitions ####
  stoch_transitions <- build_transitions(gdata)

  ###########################################################
  ### Deterministic transitions for mosquitoes life cycle ###
  ###########################################################
  # pts_fun is a post time step function in C_code updating v0 at each time step.
  # It is used for meterological and evironemental data, diapause trigger and
  # vector population stages driven by deterministic events.

  pts_fun <- build_pts_fun(u0,
                           v0,
                           gdata,
                           ldata,
                           vector,
                           virus,
                           diapause_interv,
                           TS_sim,
                           prev_control,
                           ref_norm)

  gc()

  ###################
  ### Simulations ###
  ###################

  # u0[1, 2] <- 1000
  # u0[, 7] <- 1000

  # start_time <- Sys.time()

  if(verbose)
    message("## Build the model ##")
  # message(Sys.time())

  if(is.null(introduction_pts)){

    model  <- mparse(
      transitions = stoch_transitions,
      compartments = u0 %>% colnames,
      gdata = gdata,
      ldata = ldata,
      u0 = u0,
      v0 = v0,
      tspan = TS_sim$time_serie_num, # number of days simulated. Start at 0 to get the indexing correct in the post-time-step function.
      pts_fun = pts_fun
    )

    if(verbose)
    message("## Run simulations ##")
    output <- runsimulations(model, n_sim, TS_sim, parcels, introduction_pts)

  } else {

    ###########################################
    ### Introduction of exposed individuals ###
    ###########################################

    # E Matrix for the select process
    E <- structure(.Data = c(names(u0) == "Sh", #1 Human host - susceptible
                             names(u0) == "Eh", #2 Human host - exposed
                             names(u0) == "Ih", #3 Human host - infected
                             names(u0) == "Rh", #4 Human host - recovered
                             names(u0) %in% c("Sh", 'Eh', "Ih", "Rh"), #5 Human host - anyone
                             startsWith(names(u0), "A1h") | startsWith(names(u0), "A1o") | startsWith(names(u0), "A2h") | startsWith(names(u0), "A2o"),  #6 Mosquito vector - any exposed or infected adult
                             startsWith(names(u0), "A")  #7 Mosquito vector - any exposed or infected adult
    ) %>% as.numeric,
    .Dim = c(length(u0 %>% colnames), 7),
    .Dimnames = list(u0 %>% colnames,
                     c("1", "2", "3", "4", "5", "6","7"))
    )

    # N matrix for the shift process
    N <- matrix(rep(0, length(u0 %>% colnames)),
                nrow = length(u0 %>% colnames), ncol = 2,
                dimnames = list(u0 %>% colnames,
                                c("1", "2")))

    model  <- mparse(
      transitions = stoch_transitions,
      compartments = u0 %>% colnames,
      gdata = gdata,
      ldata = ldata,
      u0 = u0,
      v0 = v0,
      tspan = TS_sim$time_serie_num, # number of days simulated. Start at 0 to get the indexing correct in the post-time-step function.
      pts_fun = pts_fun,
      # introduction of exposed individuals
      events = set_introduction_pts(introduction_pts, start_date, end_date, TS_sim, parcels, u0),
      E = E,
      N = N
    )


    if(verbose)
      message("## Run simulations ##")
    output <- runsimulations(model, n_sim, TS_sim, parcels, introduction_pts)

  }

  gc()


  return(output)
}
