#' Run simulations and produce the output
#'
#' @description This function runs simulations and produces output.
#'
#' @param model siminf model
#' @param n_sim Integer. Number of simulations.
#' @param TS_sim List. Four vectors of simulated dates (dates) and simulated days (numeric) with and without the initialization period.
#' @param parcels data.frame or data.table describing the patches. Required columns: 'ID': unique identifier, 'POP': population size, 'Kfix': fix carrying capacity for larvae and pupae, 'Kvar': variable carrying capacity for larvae and pupae, 'STATION': meteorological station identifier (optional), 'DIFF_ALT': difference between meteorological station altitude and average altitude of the patch (optional).
#' @param introduction_pts data.frame or data.table describing the introduction of individuals. Can be generated by [build_E_random()] function (see function documentation for additional details on the structure).
#'
#' @importFrom pbapply pblapply
#' @importFrom SimInf run trajectory
#' @importFrom shiny isRunning incProgress withProgress
#' @importFrom data.table data.table setattr as.data.table .SD
#'
#' @noRd

runsimulations <- function(model, n_sim, TS_sim, parcels, introduction_pts) {

  # Helper function to process a single simulation
  process_simulation <- function(x) {
    traj <- as.data.table(trajectory(run(model)))
    traj[, DATE := TS_sim$time_serie_date[time + 1], by = node]
    traj[, ID := parcels$ID[.SD$node]]
    traj <- traj[DATE %in% TS_sim$time_serie_output_d]

    if (!is.null(introduction_pts)) {
      cols <- c("ID", "DATE", "time", "Sh", "Eh", "newEggs", "Ih", "Rh", "Em", "Lm", "Pm", "Aemm",
                "A1hm", "A1gm", "A1om", "A2hm", "A2gm", "A2om", "A1gmE", "A1omE", "A2hmE",
                "A2gmE", "A2omE", "A1gmI", "A1omI", "A2hmI", "A2gmI", "A2omI", "R0",
                "ninfhL", "ninfhE", "ninfm1", "ninfm2", "interv_Am", "z", "temperature",
                "RR_day", "RR_7days", "kL", "kP", "E2I", "G2O")
    } else {
      cols <- c("ID", "DATE", "time", "Sh", "Em", "newEggs", "Lm", "Pm", "Aemm", "A1hm", "A1gm",
                "A1om", "A2hm", "A2gm", "A2om", "R0", "interv_Am", "z", "temperature",
                "RR_day", "RR_7days", "kL", "kP")
    }

    setcolorder(traj, cols)
    traj[, cols, with = FALSE]
  }

  if (shiny::isRunning() & n_sim > 1) {
    percentage <- 0
    output <- withProgress(message = "Simulations progress: ", value = 0, {
      pblapply(1:n_sim, function(x) {
        traj <- process_simulation(x)
        percentage <<- percentage + 1 / n_sim * 100
        incProgress(1 / n_sim, detail = paste(round(percentage), "%"))
        gc()
        traj
      })
    })
  } else {
    output <- pblapply(1:n_sim, function(x) {
      traj <- process_simulation(x)
      gc()
      traj
    })
  }

  # Setting attributes
  setattr(output, "ID", "identifier of the spatial unit")
  setattr(output, "DATE", "simulated day")
  setattr(output, "time", "simulated time step")


  # setattr(output, "Species", "identifier of the spatial unit")
  # setattr(output, "Virus", "identifier of the spatial unit")

  setattr(output, "Sh", "number of susceptible humans")
  setattr(output, "Eh", "number of exposed humans")
  setattr(output, "Ih", "number of infectious humans")
  setattr(output, "Rh", "number of recovered humans")
  setattr(output, "Em", "number of mosquito eggs")
  setattr(output, "Lm", "number of mosquito larvae")
  setattr(output, "Pm", "number of mosquito pupae")
  setattr(output, "Aemm", "emerging adult mosquitoes")
  setattr(output, "A1hm", "nulliparous adult mosquitoes seeking for host")
  setattr(output, "A1gm", "nulliparous adult mosquitoes gorged after blood meal")
  setattr(output, "A1om", "nulliparous adult mosquitoes seeking for oviposition site")
  setattr(output, "A2hm", "parous adult mosquitoes seeking for host")
  setattr(output, "A2gm", "parous adult mosquitoes gorged after blood meal")
  setattr(output, "A2om", "parous adult mosquitoes seeking for oviposition site")

  setattr(output, "R0", "basic reproduction number")
  setattr(output, "interv_Am", "additional death rate for adults due to control interventions")
  setattr(output, "z", "diapause (1 = Diapause, 0 = Favourable period for egg hatching)")

  gc()
  return(output)
}
