#' Set introduction point to the right format for SimInf
#'
#' @description This is an internal function to turn introduction_pts into a format that fits SimInf input.
#'
#' @param introduction_pts data.frame or data.table describing the introduction of individuals. Can be generated by [build_E_random()] function (see function documentation for additional details on the structure).
#' @param start_date Date in 'YYYY-MM-DD' format.
#' @param end_date Date in 'YYYY-MM-DD' format.
#' @param TS_sim List. Four vectors of simulated dates (dates) and simulated days (numeric) with and without the initialization period.
#' @param parcels data.frame or data.table describing the patches. Required columns: 'ID': unique identifier, 'POP': population size, 'Kfix': fix carrying capacity for larvae and pupae, 'Kvar': variable carrying capacity for larvae and pupae, 'STATION': meteorological station identifier (optional), 'DIFF_ALT': difference between meteorological station altitude and average altitude of the patch (optional).
#' @param u0 data.frame describing the initial population stage for each compartment in each parcel. Can be generated by [iniState()] function (see documentation of the function for more details on the structure).
#'
#' @return The modified introduction_pts data.frame or data.table.
#'
#' @noRd

set_introduction_pts <- function(introduction_pts, start_date, end_date, TS_sim, parcels, u0) {

  # Ensure dates are in Date format
  start_date <- as.Date(start_date)
  end_date <- as.Date(end_date)

  # Validate introduction dates
  if (any(!introduction_pts$time %in% seq.Date(from = start_date, to = end_date, by = "day"))) {
    warning(paste0(
      "At least one introduction occurs outside the simulation period:\n",
      paste(introduction_pts[!introduction_pts$time %in% seq.Date(from = start_date, to = end_date, by = "day")], collapse = "\n")
    ))
  }

  # Convert introduction times to simulation time points
  introduction_pts$time <- match(introduction_pts$time, TS_sim$time_serie_date) - 1

  # Convert destination IDs to numerical IDs
  introduction_pts$node <- match(introduction_pts$dest, parcels$ID)

  # Select the stage
  introduction_pts$select <- match(introduction_pts$select, colnames(u0))

  # Add event details
  introduction_pts$event <- "enter"
  introduction_pts$dest <- 0
  introduction_pts$proportion <- 0
  introduction_pts$shift <- 0

  # Check for NA values and stop if found
  if (any(is.na(introduction_pts))) {
    stop("introduction_pts format is not respected.\n",
         "IDs in 'node' columns must be in parcels ID.\n",
         "Dates in 'time' must be included in the simulated period.\n",
         "Epidemiological stages in 'select' must be among the following stages: 'Sh', 'Eh', 'Ih', 'Rh', 'A1gmI', 'A1omI', 'A2hmI', 'A2gmI', 'A2omI'.")
  }

  return(introduction_pts)
}
